<?php
namespace Aura\Framework\Cli\Server;

use Aura\Framework\Cli\AbstractCommandTest;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-20 at 11:31:13.
 */
class CommandTest extends AbstractCommandTest
{
    /**
     * @covers Aura\Framework\Cli\Server\Command::setPhp
     * @todo   Implement testSetPhp().
     */
    public function testSetPhp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Aura\Framework\Cli\Server\Command::action
     * @todo   Implement testAction().
     */
    public function testAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
