<?php
namespace Aura\Framework\Bootstrap;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-20 at 08:18:01.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $factory;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // use the real system root
        $root = null;
        $map = ['mock' => 'Aura\Framework\Mock\Bootstrap'];
        $this->factory = new Factory($root, $map);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Aura\Framework\Bootstrap::exec
     * @todo   Implement testExec().
     */
    public function testExec()
    {
        $bootstrap = $this->factory->newInstance('mock');
        $this->assertInstanceOf('Aura\Framework\Mock\Bootstrap', $bootstrap);
    }
}
